name: Auto add games

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install aiohttp

    - name: Run script
      run: python auto.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add games/ games.json iframe/ sitemap.xml newsitemap.xml
        git commit -m "Add new games" || echo "no new games"
        git push
